---
- name: install apache and php
  package:
    name:
      - httpd
      - php
    state: latest
    update_cache: yes

- name: start httpd (CentOS)
  tags: apache,centos,httpd
  service:
    name: httpd
    state: started
    enabled: true
 
- name: install mariadb package (CentOS)
  tags: centos,db,mariadb
  package:
    name: mariadb-server
    state: latest

- name: "Mariadb- Restarting/Enabling"
  service:
    name: mariadb
    state: restarted
    enabled: true
