---

- hosts: all
  become: true
  pre_tasks:

  - name: Update and upgrade remote CentOS server
    dnf:
      update_cache: yes
      name:  "*"
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Installing installations dependencies
    apt:
      name:
        - wget
      state: latest
    when: ansible_distribution == "Ubuntu"
  
  - name: Dpkg fixing in Ubuntu Servers
    shell: |
      dpkg --configure -a
    when: ansible_distribution == "Ubuntu"

  - name: Update and upgrade remote in Ubuntu servers
    apt:
      update_cache: yes
      upgrade: yes
    when: ansible_distribution == "Ubuntu"


- hosts: centos
  become: true
  roles:
    - elkCentOS

- hosts: ubuntu
  become: true
  roles:
    - elkUbuntu

- hosts: centos
  become: true
  roles:
    - nagiosCentOS

- hosts: igp_centos
  become: true
  roles: 
    - prometheusCentOS

- hosts: ubuntu
  become: true
  roles: 
    - prometheusUbuntu


- hosts: centos
  become: true
  roles: 
    - lsCentOS

- hosts: ubuntu
  become: true
  roles: 
    - lsUbuntu
