---
- name: install apache and php for Ubuntu servers
  tags: apache,apache2,ubuntu
  package:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
    update_cache: yes

- name: install mariadb package (Ubuntu)
  tags: db, mariadb,ubuntu
  package:
    name: mariadb-server
    state: latest

- name: "Mariadb- Restarting/Enabling"
  service:
    name: mariadb
    state: restarted
    enabled: true
